language: go
go:
  - 1.16.x
os:
  - linux
  - osx
env:
  - CODACY_PROJECT_TOKEN=985771987a4042869ac4b4437d0aedb5c95cf97d
dist: trusty
install: true
before_script:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) download
script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test -coverprofile=coverage.out -v ./tests/*
after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)
