language: go
go:
  - 1.16.x
os:
  - linux
  - osx
env:
  - CODACY_PROJECT_TOKEN=0d93d3ba284543ecb3c41dbc7544d8b1 CODECLIMATE_API_HOST=https://codebeat.co/webhooks/code_coverage CODECLIMATE_REPO_TOKEN=8ad64015-9459-4c8e-ad69-a5531972a966 CC_TEST_REPORTER_ID=e12b9018a5298c8ad598bebbdf2cc929db0bcd1ed6f18afc581dbf33f63243cf
dist: trusty
install: true
before_script:
  - ./scripts/download-codeclimate.sh
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test -race -json ./tests/... -covermode=atomic -coverpkg=./... -coverprofile=cover.out
after_success:
  - ./cc-test-reporter format-coverage --debug -t gocov --prefix github.com/mw3tv123/go-notify cover.out
  - ./cc-test-reporter upload-coverage
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report --force-coverage-parser go -r cover.out
